import type { Metadata } from "next";
import "../styles/global.scss";
import HeaderApp from "src/components/header/HeaderApp";

export const metadata: Metadata = {
  title: "Create Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HeaderApp />
        {children}
      </body>
    </html>
  );
}
